import './globals.css'
import { Mulish } from 'next/font/google'

const mulish = Mulish({ subsets: ['latin']})

export const metadata = {
  title: 'Portfolio - Narcy Alcantara',
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mulish.className}>{children}</body>
    </html>
  )
}